### PR TITLE
Update Ex_2.6_setbits.c

### PR DESCRIPTION
**Pull request by attentiveanuj**
the return statement is wrong 
it should be 
return x &((~0<<p+1) | ~(~0<<(p+1-n))) | ((y&~(~0<<n))<<(p+1-n));

### CODE REVIEW

**Comment by attentiveanuj** [comment]
the return statement is wrong 
try x = 16 
p = 4
n = 4
y = 8
ans should be 16

**Comment by fherrera124** [comment]
your version doesn't pass all my tests. Here is my version:

```
#include <assert.h>

unsigned setbits(unsigned x, int p, int n, unsigned y) {
    return x & ((~0 << p + 1) | ~(~0 << p + 1 - n)) | ((y & ~(~0 << n)) << p + 1 - n);
}

int main(void) {
    assert(setbits(0x2, 2, 2, 0xD) == 0x2);    /* x=0(01)0     y=11(01)      : no changes */
    assert(setbits(0xF, 3, 1, 0xE) == 0x7);    /* x=(1)111     y=111(0)      : 0111 */
    assert(setbits(0x37, 3, 2, 0x4E) == 0x3B); /* x=0011(01)11 y=0100011(10) : 00111011 */
    assert(setbits(0xFF, 3, 4, 0x00) == 0xF0); /* x=1111(1111) y=0000(0000)  : 11110000 */

    return 0;
}
```

**Review by fherrera124 — CHANGES_REQUESTED** [review]
Your version doesn't pass all my tests. Here is my version:
```
#include <assert.h>

unsigned setbits(unsigned x, int p, int n, unsigned y) {
    return x & ((~0 << p + 1) | ~(~0 << p + 1 - n)) | ((y & ~(~0 << n)) << p + 1 - n);
}

int main(void) {
    assert(setbits(0x2, 2, 2, 0xD) == 0x2);    /* x=00000(01)0  y=000011(01) : equal to x */
    assert(setbits(0x2, 0, 0, 0xD) == 0x2);    /* x=00000010    y=00001101   : equal to x */
    assert(setbits(0xF, 3, 1, 0xE) == 0x7);    /* x=0000(1)111  y=0000111(0) : 0000(0)111 */
    assert(setbits(0x37, 3, 2, 0x4E) == 0x3B); /* x=0011(01)11  y=010011(10) : 0011(10)11 */
    assert(setbits(0x37, 7, 8, 0x4E) == 0x4E); /* x=(00110111)  y=(01001110) : equal to y */
    assert(setbits(0xFF, 3, 4, 0x00) == 0xF0); /* x=1111(1111)  y=0000(0000) : 1111(0000) */
    assert(setbits(0xFF, 0, 1, 0x00) == 0xFE); /* x=1111111(1)  y=0000000(0) : 1111111(0) */

    return 0;
}
```

**Comment by orsenthil** [comment]
Adopted this change. 
https://github.com/uthcode/learntosolveit/commit/0dee803ee05fabf89e7adede92c40fd7d7fc9a84

**Pull request closed without merging**
